---

- hosts: all
  become: true
  tasks:

  - name: update repository index on Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package on Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache on Ubuntu
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: enable and start apache2 on Ubuntu
    systemd:
      name: apache2
      enabled: yes
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: update repository index on CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd package on CentOS
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache on CentOS
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: enable and start httpd on CentOS
    systemd:
      name: httpd
      enabled: yes
      state: started
    when: ansible_distribution == "CentOS"

  - name: open port 80 in the firewall on CentOS
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
    when: ansible_distribution == "CentOS"

  - name: reload the firewall using command on CentOS
    command: firewall-cmd --reload
    when: ansible_distribution == "CentOS"

  - name: allow httpd to serve content in SELinux on CentOS
    command: setsebool -P httpd_can_network_connect 1
    when: ansible_distribution == "CentOS"
